### ISSUE TITLE
Prioritization EE, GIS and calculations for final report

### ISSUE THREAD

**Issue by josue-medellin** [ssj-delta-cu/ssj-overview#39]
@qjhart This is just FYI

@andybell this is for you to help prioritize issues. More of a checklist as we wrap the report.
- [ ] Resolve land inconsistencies.  We need totals for Legal Delta and Delta Service Area. #32 
- [x] Redo charts for bare soil measured versus estimated ET (Stations D1, D2, D3, D5) These should include labels in the red lines and #35 @jrmerz this is FYI. @andybell will complete this task. Just please keep me posted where R code lives.
- [x] KC charts, please remove  for SIMS the purple dots for the floating veg, riparian, water, wetland herbaceous, upland herbaceous and urban classes, since SIMS does not currently provide estimates for these regions. #37
- [x] Check bug on DETAW selection of islands: Quinn, did some recalculation.  #33  Check figure 11 and 12 in the current report. Recalculations from quinn were only for the totals.

![image](https://cloud.githubusercontent.com/assets/13739372/18827687/f646741e-8388-11e6-8320-33b8fde449f5.png)

https://docs.google.com/spreadsheets/d/183ksTSkO04K4WuIjI7Q2oxxmvbJswxVjTOXPlMBQKAk/edit#gid=1606824585
- [x] Inmmature orchards. Are we including this in the calculations #38

**Comment by andybell** [comment]
- [x]  KC charts, please remove for SIMS the purple dots for the floating veg, riparian, water, wetland herbaceous, upland herbaceous and urban classes, since SIMS does not currently provide estimates for these regions. #37
