### ISSUE TITLE
Data Update Checklist

### ISSUE THREAD

**Issue by nickrsan** [ssj-delta-cu/ssj-overview#46]
Hey Andy, I'm making this a checklist that we can use as a template whenever we get/change results from a group so that we can make sure that any downstream analyses get handled.

- [ ] Output new GeoJSON
- [ ] Create new graphs for report from GeoJSON
- [ ] Load new graphs into report (we can maybe specify which graphs, but it'll vary)
- [ ] Download new monthly raster
- [ ] Update comparison maps

Anything missing?

**Comment by ghost** [comment]
It seems that this is intended for Andy B?

**Comment by nickrsan** [comment]
Yes, that's correct, sorry - I assigned to him too - didn't know you watched this repo. Sorry for confusion!
